""" database dependencies to support sqliteDB examples """
from random import randrange
from datetime import date
import os, base64
import json
import pickle
from __init__ import app, db
from sqlalchemy.exc import IntegrityError
from sqlalchemy import PickleType
from werkzeug.security import generate_password_hash, check_password_hash


''' Tutorial: https://www.sqlalchemy.org/library.html#tutorials, try to get into Python shell and follow along '''

# Define the Post class to manage actions in 'posts' table,  with a relationship to 'users' table

class Films(db.Model):
    __tablename2__ = 'Films'  # table name is plural, class name is singular

    # Define the User schema with "vars" from object
    _name = db.Column(db.String(255), primary_key=True, nullable=False)
    _year = db.Column(db.Integer, unique=False, nullable=False)
    _epcount = db.Column(db.Integer, unique=False, nullable=False)
    _language = db.Column(db.String(255), unique=False, nullable=False)
    _eplist = db.Column(PickleType, unique = False, nullable=False)
    # Defines a relationship between User record and Notes table, one-to-many (one user to many notes)
    posts = db.relationship("Post2", cascade='all, delete', backref='users', lazy=True)

    # constructor of a User object, initializes the instance variables within object (self)
    def __init__(self, name, year, epcount, language, my_list):
        self._eplist=pickle.dumps(my_list)
        self._name = name
        self._epcount = epcount
        self._year = year
        self._language = language# variables with self prefix become part of the object, 
    # a name getter method, extracts name from object
    @property
    def name(self):
        return self._name
    
    # a setter function, allows name to be updated after initial object creation
    @name.setter
    def name(self, name):
        self._name = name
    
   
    # output content using str(object) in human readable form, uses getter
    # output content using json dumps, this is ready for API response
    def __str__(self):
        return json.dumps(self.read())

    # CRUD create/add a new record to the table
    # returns self or None on error
    def create(self):
        #try:
            # creates a person object from User(db.Model) class, passes initializers
            db.session.add(self)  # add prepares to persist person object to Users table
            db.session.commit()  # SqlAlchemy "unit of work pattern" requires a manual commit
            return self
        #except IntegrityError:
         #   db.session.remove()
          #  return None

    # CRUD read converts self to dictionary
    # returns dictionary
    def read(self):
        return {
            "name": self.name
        }
    #"posts": [post.read() for post in self.posts]
    # CRUD update: updates user name, password, phone
    # returns self

    def update(self, name = ""):
        """only updates values with length"""
        self.name = name
        return self

    # CRUD delete: remove self
    # None
    def delete(self):
        db.session.delete(self)
        db.session.commit()
        return {"message":f"deleted {self}"}
"""Database Creation and Testing """


# Builds working data for testing
def initCountries():
    """Create database and tables"""
    db.create_all()
    """Tester data for table"""
    u1 = Countries(name='test')

    countries = [u1]

    """Builds sample user/note(s) data"""
    for country in countries:
        try:
            '''add a few 1 to 4 notes per user'''
            for num in range(randrange(1, 4)):
                note = "#### " + country.name + " note " + str(num) + ". \n Generated by test data."
                country.posts.append(Post2(id=country.id, note=note, image='ncs_logo.png'))
            '''add user/post data to table'''
            country.create()
        except IntegrityError:
            '''fails with bad or duplicate data'''
            db.session.remove()
            print(f"Records exist, duplicate email, or error: {country.id}")
            