version: '3'
services:
        web:
                image: Quintic Port # Change the image name to something unique
                build: .
                ports:
                        - "8000:8080" # Edit the number on the left to match the port you chose
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped