version: '3'
services:
        web:
                image: Quintic Port # Change the image name to something unique
                build: .
                ports:
                        - "8086:8086"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped